### ISSUE TITLE
Numerous issues with your code

### ISSUE THREAD

**Issue by relative** [pxldotblue/frontend-but-better-v4#1]
Hi!

While looking over at your source I've seen numerous issues that should be addressed:

## Mixed indentation
Taking a look at [/index.html](https://github.com/pxldotblue/frontend-but-better-v4/blob/c543a43185c08a4d0fd086c9deb2b8be53e7c6c0/index.html) we will observe numerous instances of indentation being incorrect, especially on [lines 10 and 11](https://github.com/pxldotblue/frontend-but-better-v4/blob/c543a43185c08a4d0fd086c9deb2b8be53e7c6c0/index.html#L10-L11).

This is not healthy for collaboration and should be solved.

## Incorrect closing type for meta tag
Taking a look at [Line 11 of /index.js](https://github.com/pxldotblue/frontend-but-better-v4/blob/c543a43185c08a4d0fd086c9deb2b8be53e7c6c0/index.html#L11) we will observe that the meta tag is not closed, despite an inline closing expression in the meta tags on the following lines ([Line 12-13](https://github.com/pxldotblue/frontend-but-better-v4/blob/c543a43185c08a4d0fd086c9deb2b8be53e7c6c0/index.html#L12-L13))

I hope to see the issues I've reported resolved by you.

Best regards,
relative

**Comment by q-woen-p** [comment]
thanks gdem skidem fixing now ennit

**Comment by relative** [comment]
I have seen your attempt at correcting the issues I've reported but I still see an example of mixed indentation.

**Comment by q-woen-p** [comment]
sorry can you please show what lines as i am dyslexic

**Comment by q-woen-p** [comment]
i think i have fixered it can you please check and confirm 

love, 
woen <3

**Comment by ElpersonPL** [comment]
your mother

**Comment by PrintScrn** [comment]
can i have a cheese toastie please

**Comment by relative** [comment]
Yeah looks good to me mate
